name: healthcare_app
description: A healthcare application
publish_to: 'none'

version: 2.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  intl: ^0.18.1
  url_launcher: ^6.1.14
  file_picker: ^9.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fruit.jpeg
    - assets/covid.png
    - assets/user.jpg
    - assets/Paracetamol.jpg
    - assets/netmeds_logo.png
